[build]
  command = ""
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas", "sharp"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  port = 8888
  autoLaunch = false

